project:
  name: NFT-COLLECTION
  version: 0.1.0
github:
  token: ${GITHUB_TOKEN}
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
dotenv: .env
networks:
  goerli:
    vrf_coordinator: '0x2bce784e69d2Ff36c71edcB9F88358dB0DfB55b4'
    link_token: '0x326C977E6efc84E512bB9C30f76E30c160eD06FB'
    verify: True
    keyhash: "0x0476f9a745b61ea5c0ab224d3a6e4c99f0b02fce4da01143a4f70aa80ae76e8a"
    fee: 300000000000000000
  sepolia:
    vrf_coordinator: '0x8103b0a8a00be2ddc778e6e7eaa21791cd364625'
    link_token: '0x779877a7b0d9e8603169ddbd7836e478b4624789'
    verify: True
    keyhash: "0x474e34a077df58807dbe9c96d3c009b23b3c6d0cce433e59bbf5b34f823bc56c"
    fee:  30000000000
wallets:
  from_key: ${PRIVATE_KEY}